minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@sveltejs/*'
  - svelte
  - esrap
  - devalue
  - zimmerframe
  - prettier-plugin-svelte
  - svelte-check
  - esm-env
  - twoslash-svelte # NOTE: Remove this exclusion before this PR is merged
blockExoticSubdeps: true

packages:
  - 'apps/*'
  - 'packages/*'
