minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@sveltejs/*'
  - svelte
  - sv
  - esrap
  - devalue
  - zimmerframe
  - prettier-plugin-svelte
  - svelte-check
  - esm-env
blockExoticSubdeps: true
engineStrict: true
allowBuilds:
  esbuild: true
  sharp: true
  svelte-preprocess: true

packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': ^22.19.20
  vite: ^8.0.16
  vitest: ^4.1.8

overrides:
  # This is a workaround to avoid the "exotic dependency is not allowed in subdependencies"
  # error that pnpm throws when `blockExoticSubdeps` is enabled
  'sv>@sveltejs/sv-utils': '-'
