minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@sveltejs/*'
  - svelte
  - sv
  - esrap
  - devalue
  - zimmerframe
  - prettier-plugin-svelte
  - svelte-check
  - esm-env
blockExoticSubdeps: true

packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  # This is a workaround to avoid the "exotic dependency is not allowed in subdependencies"
  # error that pnpm throws when `blockExoticSubdeps` is enabled
  'sv>@sveltejs/sv-utils': '-'
