name: "Documentation Request"
description: Request enhanced/new documentation
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request enhancements to the documentation! Please be concise and clear in your request, vague requests may not be actionable and may be closed.
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: Please provide a clear and concise description the problem enhanced documentation would solve / the confusion it would clear up. The more information you can provide here, the better.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the proposed solution
      description: Please provide a clear and concise description of what you would like to happen.
      placeholder: I would like to see...
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this documentation to you?
      options:
        - nice to have
        - would make my life easier
        - i cannot use svelte without it
    validations:
      required: true
