name: Docs preview delete

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name (not fully-qualified, eg. `svelte` or `kit`)'
        required: true
        type: string
      pr:
        description: 'PR number'
        required: true
        type: string

env:
  BRANCH: preview-${{ inputs.repo }}-${{ inputs.pr }}

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Delete branch
        run: git push origin :${{ env.BRANCH }}
