name: Docs preview delete

on:
  repository_dispatch:
    types: [docs-preview-delete]

env:
  BRANCH: preview-${{ github.event.client_payload.package }}-${{ github.event.client_payload.pr }}

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Delete branch
        run: git push origin :${{ env.BRANCH }}
