name: Sync docs

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name (not fully-qualified, eg. `svelte` or `kit`)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - name: Sync
        run: cd apps/svelte.dev && pnpm sync-docs -p ${{ inputs.repo }}

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: sync ${{ inputs.repo }} docs
          title: Sync `${{ inputs.repo }}` docs
          body: This is an automated pull request. See the [README](../tree/main/apps/svelte.dev/scripts/sync-docs/README.md) for more information
          branch: sync-${{ inputs.repo }}
          base: main
