name: Sync docs

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name (not fully-qualified, eg. `svelte` or `kit`)'
        required: true
        type: choice
        options:
          - svelte
          - kit
          - cli
          - ai-tools

permissions:
  contents: write
  pull-requests: write

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - name: Sync
        run: cd apps/svelte.dev && pnpm sync-docs -p "${{ inputs.repo }}#${{ inputs.repo }}#main"

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          commit-message: sync ${{ inputs.repo }} docs
          title: Sync `${{ inputs.repo }}` docs
          body: This is an automated pull request. See the [README](../tree/main/apps/svelte.dev/scripts/sync-docs/README.md) for more information
          branch: sync-${{ inputs.repo }}
          base: main
